In [1]:
import pymysql
    # Establish the connection
connection = pymysql.connect(
        host="localhost",
        port=3306,
        user="root",
        password="priya"
    )
cursor = connection.cursor()

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("eq_data_cleaned.csv")

In [4]:
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://root:priya@localhost:3306/eq_database')

df.to_sql("earthquake_table",if_exists= "replace",con = engine) # sqlalchemy

112674

In [5]:
cursor.execute("SELECT * FROM eq_database.earthquake_table")

112674

In [6]:
results = cursor.fetchall()
results = pd.DataFrame(results)
results.head()

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,0,us6000ddi8,2021-01-31 23:20:49.923,2021-04-16 19:02:44.040,-31.7493,-68.9337,17.27,4.7,mwr,"29 km SW of Villa Basilio Nievas, Argentina",...,2021,1,January,31,2021-01-31,7,Sunday,argentina,23,20
1,1,us6000dev6,2021-01-31 23:08:17.161,2021-04-16 19:03:47.040,-15.4902,-177.2052,426.71,4.1,mb,Fiji region,...,2021,1,January,31,2021-01-31,7,Sunday,alaska,23,8
2,2,us6000dev5,2021-01-31 22:54:19.760,2021-04-16 19:03:47.040,19.7529,121.3159,46.73,4.7,mb,"103 km SW of Basco, Philippines",...,2021,1,January,31,2021-01-31,7,Sunday,philippines,22,54
3,3,us6000ddhs,2021-01-31 22:06:00.832,2021-04-16 19:02:43.040,28.1524,57.2570,10.00,4.9,mb,"114 km N of M?n?b, Iran",...,2021,1,January,31,2021-01-31,7,Sunday,iran,22,6
4,4,us6000dev4,2021-01-31 21:51:14.016,2021-04-16 19:03:46.040,71.3212,-3.7578,10.00,4.0,mb,"184 km ENE of Olonkinbyen, Svalbard and Jan Mayen",...,2021,1,January,31,2021-01-31,7,Sunday,svalbard and jan mayen,21,51

Q1. Top 10 strongest earthquakes.

In [7]:
cursor.execute("""
               SELECT id, date, country, mag 
               FROM eq_database.earthquake_table 
               ORDER BY mag DESC
               LIMIT 10;""")   
Q1_results = cursor.fetchall()
Q1_results = pd.DataFrame(Q1_results, columns=['id', 'date', 'country', 'mag'])
Q1_results

             id        date                            country  mag
0    us6000qw60  2025-07-29                  russia earthquake  8.8
1  ak0219neiszm  2021-07-29                  alaska earthquake  8.2
2    us6000f53e  2021-08-12                             alaska  8.1
3    us7000dflf  2021-03-04             new zealand earthquake  8.1
4    us7000qx2g  2025-09-18                             russia  7.8
5    us6000jllz  2023-02-06  kahramanmaras earthquake sequence  7.8
6    us6000kd0n  2023-05-19                             alaska  7.7
7    us6000dg77  2021-02-10                             alaska  7.7
8    us7000pn9s  2025-03-28         burma (myanmar) earthquake  7.7
9    us7000pcdl  2025-02-08                     cayman islands  7.6

Q2. Top 10 deepest earthquakes.

In [8]:
cursor.execute("""
               SELECT id, date, country, depth_km 
               FROM eq_database.earthquake_table 
               ORDER BY depth_km DESC 
               LIMIT 10;""")   
Q2_results = cursor.fetchall()
Q2_results = pd.DataFrame(Q2_results, columns=['id', 'date', 'country','depth_km'])
Q2_results

           id        date  country  depth_km
0  us6000sp3p  2026-04-02  vanuatu   683.578
1  us6000k2db  2023-04-01  vanuatu   681.238
2  us7000kxdn  2023-09-18   alaska   675.265
3  us6000mivr  2024-03-08   alaska   671.043
4  us6000rk66  2025-10-29     fiji   669.556
5  us6000f2w3  2021-08-01     fiji   669.460
6  us7000q1jk  2025-05-10     fiji   667.237
7  us7000s0st  2026-02-14     fiji   667.197
8  us6000dhfx  2021-02-13   alaska   664.740
9  us7000he64  2022-06-01     fiji   664.700

Q3. Shallow earthquakes < 50 km and mag > 7.5.

In [9]:
cursor.execute("""
               SELECT id, time, country, mag, depth_km 
               FROM eq_database.earthquake_table 
               WHERE depth_km < 50 and mag > 7.5 
               ORDER BY depth_km;""")
Q3_results = cursor.fetchall()
Q3_results = pd.DataFrame(Q3_results, columns=['id', 'time', 'country', 'mag', 'depth_km'])
Q3_results

,id,time,country,mag,depth_km
0,us6000rgf4,2025-10-10 20:29:20.075,alaska,7.6,5.639
1,us6000dg77,2021-02-10 13:19:55.530,alaska,7.7,10.000
2,us6000jllz,2023-02-06 01:17:34.342,kahramanmaras earthquake sequence,7.8,10.000
3,us7000pn9s,2025-03-28 06:20:52.715,burma (myanmar) earthquake,7.7,10.000
4,us7000pcdl,2025-02-08 23:23:14.697,cayman islands,7.6,14.326
5,us6000kd0n,2023-05-19 02:57:03.172,alaska,7.7,18.053
6,us6000f53e,2021-08-12 18:35:17.231,alaska,8.1,22.790
7,us7000i9bw,2022-09-19 18:05:08.217,mexico,7.6,26.943
8,us7000qx2g,2025-09-18 18:58:14.939,russia,7.8,27.000
9,us7000dflf,2021-03-04 19:28:33.178,new zealand earthquake,8.1,28.930
10,ak0219neiszm,2021-07-29 06:15:49.188,alaska earthquake,8.2,35.000
11,us6000qw60,2025-07-29 23:24:52.483,russia earthquake,8.8,35.000
12,us7000lff4,2023-12-02 14:37:04.454,philippines,7.6,40.000
13,us6000rtdt,2025-12-08 14:15:09.896,japan earthquake,7.6,40.720

Q4. Average depth per continent.

NOTE: DATA NOT SUFFIECIENT

Q5. Average magnitude per magnitude type.

In [10]:
cursor.execute("""
               SELECT magType, avg(mag) as avg_mag 
               FROM eq_database.earthquake_table
               GROUP BY magType 
               ORDER BY avg(mag) DESC;""")
Q5_results = cursor.fetchall()
Q5_results = pd.DataFrame(Q5_results, columns=['magType', 'avg_mag'])
Q5_results

       magType   avg_mag
0          mwc  6.150000
1        ms_20  5.800000
2          mwb  5.800000
3          mww  5.368714
4          mwp  5.250000
5        ms_vx  4.600000
6           mb  4.423340
7          mwr  4.331168
8           mh  4.100000
9           mw  3.935982
10         mlr  3.480000
11         mlv  3.469288
12          md  3.440955
13  ml(texnet)  3.367442
14         mlg  3.300000
15          ml  3.274621
16       mb_lg  3.204878

Q6. Year with most earthquakes.

In [11]:
cursor.execute("""SELECT year, count(year) as earthquake_count 
               FROM eq_database.earthquake_table 
               GROUP BY year 
               ORDER BY earthquake_count DESC
               LIMIT 1;""")
Q6_results = cursor.fetchall()
Q6_results = pd.DataFrame(Q6_results, columns=['year', 'earthquake_count'])
Q6_results

   year  earthquake_count
0  2025             22818

Q7. Month with highest number of earthquakes.

In [12]:
cursor.execute("""
               SELECT month,month_name, count(month) as earthquake_count 
               FROM eq_database.earthquake_table 
               GROUP BY month, month_name 
               ORDER BY earthquake_count DESC 
               LIMIT 1;""")
Q7_results = cursor.fetchall()
Q7_results = pd.DataFrame(Q7_results, columns=['month','month_name','earthquake_count'])
Q7_results

   month month_name  earthquake_count
0      3      March             10896

Q8. Day of week with most earthquakes.

In [13]:
cursor.execute("""
               SELECT day_of_week, day_name, count(day_of_week) as earthquake_count 
               FROM eq_database.earthquake_table 
               GROUP BY day_of_week, day_name
               ORDER BY earthquake_count DESC 
               LIMIT 1;""")
Q8_results = cursor.fetchall()
Q8_results = pd.DataFrame(Q8_results, columns=['day_of_week', 'day_name', 'earthquake_count'])
Q8_results

   day_of_week day_name  earthquake_count
0            2  Tuesday             16270

Q9. Count of earthquakes per hour of day.

In [14]:
cursor.execute("""
               SELECT hour,count(hour) as earthquake_count 
               FROM eq_database.earthquake_table 
               GROUP BY hour 
               ORDER BY hour ASC;""")
Q9_results = cursor.fetchall()
Q9_results = pd.DataFrame(Q9_results, columns=['hour', 'earthquake_count'])
Q9_results

    hour  earthquake_count
0      0              4667
1      1              4949
2      2              4782
3      3              5007
4      4              4965
5      5              4626
6      6              4546
7      7              4691
8      8              4675
9      9              4652
10    10              4513
11    11              4426
12    12              4394
13    13              4647
14    14              4502
15    15              4635
16    16              4546
17    17              4663
18    18              4720
19    19              4757
20    20              4778
21    21              4988
22    22              4869
23    23              4676

Q10.   Most active reporting network (net).

In [15]:
cursor.execute("""
               SELECT net, count(net) as active_net_count 
               FROM eq_database.earthquake_table 
               GROUP BY net 
               ORDER BY active_net_count DESC 
               LIMIT 1;""")
Q10_results = cursor.fetchall()
Q10_results = pd.DataFrame(Q10_results, columns=['net', 'active_net_count'])
Q10_results

  net  active_net_count
0  us             98535

Q11.  Top 5 places with highest casualties.

In [16]:
cursor.execute("""
               SELECT place, max(felt) as highest_casualities 
               FROM eq_database.earthquake_table 
               GROUP BY place 
               ORDER BY highest_casualities DESC
               LIMIT 5;""")
Q11_results = cursor.fetchall()
Q11_results = pd.DataFrame(Q11_results, columns=['place','highest_casualities'])
Q11_results

                                   place  highest_casualities
0  2024 Tewksbury, New Jersey Earthquake             184662.0
1       21 km SE of Greenback, Tennessee              45934.0
2                   5 km S of Julian, CA              42594.0
3          9 km SE of York Harbor, Maine              42440.0
4           1 km SE of Boulder Creek, CA              33073.0

Q12.  Total estimated economic loss per continent.

NOTE: DATA NOT SUFFICIENT

Q13.  Average economic loss by alert level.

In [17]:
cursor.execute("""
               SELECT alert, avg(cdi) as avg_eco_loss 
               FROM eq_database.earthquake_table 
               GROUP BY alert 
               ORDER BY avg_eco_loss DESC;""")
Q13_results = cursor.fetchall()
Q13_results = pd.DataFrame(Q13_results, columns=['alert', 'avg_eco_loss'])
Q13_results

    alert  avg_eco_loss
0     red      8.241667
1  orange      7.501134
2  yellow      6.764611
3   green      3.220091

Q14.  Count of reviewed vs automatic earthquakes (status).

In [18]:
cursor.execute("""
               SELECT status, count(status) as earthquake_count
               FROM eq_database.earthquake_table 
               GROUP BY status 
               ORDER BY earthquake_count DESC;""")
Q14_results = cursor.fetchall()
Q14_results = pd.DataFrame(Q14_results, columns=['status', 'earthquake_count'])
Q14_results

      status  earthquake_count
0   reviewed            112503
1  automatic               171

Q15.  Count by earthquake type (type).

In [19]:
cursor.execute("""SELECT type, count(type) as earthquake_type 
               FROM eq_database.earthquake_table 
               GROUP BY type 
               ORDER BY earthquake_type DESC;""")
Q15_results = cursor.fetchall()
Q15_results = pd.DataFrame(Q15_results, columns=['type', 'earthquake_type'])
Q15_results

                     type  earthquake_type
0              earthquake           111825
1        mining explosion              806
2               ice quake               13
3       volcanic eruption               12
4             other event                5
5               landslide                4
6  experimental explosion                3
7           mine collapse                3
8            quarry blast                2
9               explosion                1

Q16.  Number of earthquakes by data type (types).

In [20]:
cursor.execute("""
               SELECT types, count(types) AS eq_count 
               FROM eq_database.earthquake_table 
               GROUP BY types 
               ORDER BY eq_count DESC;""")
Q16_results = cursor.fetchall()
Q16_results = pd.DataFrame(Q16_results, columns=['types', 'eq_count'])
Q16_results

                                                 types  eq_count
0                ,,o,r,i,g,i,n,,,p,h,a,s,e,-,d,a,t,a,,     85694
1      ,,d,y,f,i,,,o,r,i,g,i,n,,,p,h,a,s,e,-,d,a,t,a,,      8631
2    ,,e,a,r,t,h,q,u,a,k,e,-,n,a,m,e,,,o,r,i,g,i,n,...      2172
3    ,,o,r,i,g,i,n,,,p,h,a,s,e,-,d,a,t,a,,,s,h,a,k,...      2156
4    ,,m,o,m,e,n,t,-,t,e,n,s,o,r,,,o,r,i,g,i,n,,,p,...      1350
..                                                 ...       ...
572  ,,e,v,e,n,t,-,s,e,q,u,e,n,c,e,,,g,r,o,u,n,d,-,...         1
573  ,,d,y,f,i,,,e,v,e,n,t,-,s,e,q,u,e,n,c,e,,,l,o,...         1
574  ,,d,y,f,i,,,e,v,e,n,t,-,s,e,q,u,e,n,c,e,,,f,o,...         1
575  ,,d,y,f,i,,,e,v,e,n,t,-,s,e,q,u,e,n,c,e,,,f,o,...         1
576  ,,a,s,s,o,c,i,a,t,e,,,d,y,f,i,,,g,r,o,u,n,d,-,...         1

[577 rows x 2 columns]

Q17.  Average RMS and gap per continent.

NOTE: NO SUFFIIENT DATA

Q18.  Events with high station coverage (nst > threshold).

In [21]:
cursor.execute("""
               SELECT id,date, place, nst
               FROM eq_database.earthquake_table 
               WHERE nst > 50 
               ORDER BY nst DESC;""")
Q18_results = cursor.fetchall()
Q18_results = pd.DataFrame(Q18_results, columns=['id', 'date', 'place', 'nst'])
Q18_results

,id,date,place,nst
0,us6000m12f,2024-01-02,"11 km W of Anamizu, Japan",619.0
1,us6000qzfl,2025-08-09,"120 km ENE of Ozernovskiy, Russia",566.0
2,us7000rluk,2026-01-01,"111 km N of Yakutat, Alaska",516.0
3,us7000pvtr,2025-04-29,Macquarie Island region,475.0
4,usd001097k,2023-12-11,"49 km WNW of San Antonio de los Cobres, Argentina",466.0
...,...,...,...,...
24663,us6000pllz,2025-01-10,"66 km NE of Hami, China",51.0
24664,us6000plg5,2025-01-09,"233 km E of Levuka, Fiji",51.0
24665,us6000phsb,2025-01-04,"28 km NNW of Āwash, Ethiopia",51.0
24666,us6000phph,2025-01-03,"32 km WSW of Illapel, Chile",51.0
24667,us6000phc7,2025-01-03,"12 km NW of Āwash, Ethiopia",51.0

Q19.  Number of tsunamis triggered per year.

In [22]:
cursor.execute("""
               SELECT year, COUNT(year) AS tsunami_count 
               FROM eq_database.earthquake_table WHERE tsunami = 1 
               GROUP BY year 
               ORDER BY year ASC;""")
Q19_results = cursor.fetchall()
Q19_results = pd.DataFrame(Q19_results, columns=['year', 'tsunami_count'])
Q19_results

   year  tsunami_count
0  2021            114
1  2022            136
2  2023            119
3  2024            114
4  2025            142
5  2026             34

Q20.  Count earthquakes by alert levels (red, orange, etc.).

In [23]:
cursor.execute("""
               SELECT alert, COUNT(alert) AS earthquake_count 
               FROM eq_database.earthquake_table 
               GROUP BY alert 
               ORDER BY earthquake_count DESC;""")
Q20_results = cursor.fetchall()
Q20_results = pd.DataFrame(Q20_results,columns=['alert', 'earthquake_count'])
Q20_results

    alert  earthquake_count
0   green            112498
1  yellow               129
2     red                24
3  orange                23

Q21.Find the top 5 countries with the highest average magnitude of earthquakes in the past 5 years

In [24]:
cursor.execute("""
               SELECT country, avg(mag) as average_magnitude 
               FROM eq_database.earthquake_table 
               GROUP BY country 
               ORDER BY average_magnitude DESC limit 5;""")
Q21_results = cursor.fetchall()
Q21_results = pd.DataFrame(Q21_results, columns=['country', 'average_magnitude'])
Q21_results

                             country  average_magnitude
0                  russia earthquake           8.100000
1             new zealand earthquake           8.100000
2         burma (myanmar) earthquake           7.700000
3  kahramanmaras earthquake sequence           7.650000
4                  alaska earthquake           7.566667

22.Find countries that have experienced both shallow and deep earthquakes within the same month.

In [25]:
cursor.execute("""
               SELECT country, year, month 
               FROM eq_database.earthquake_table 
               GROUP BY country, year, month 
               HAVING SUM(depth_km <= 70) > 0 
               AND SUM(depth_km > 300) > 0;""")
Q22_results = cursor.fetchall()
Q22_results = pd.DataFrame(Q22_results, columns=['country', 'year', 'month'])
Q22_results

               country  year  month
0               alaska  2021      1
1          philippines  2021      1
2            indonesia  2021      1
3    wallis and futuna  2021      1
4         japan region  2021      1
..                 ...   ...    ...
717          indonesia  2026      5
718              tonga  2026      5
719               fiji  2026      5
720              italy  2026      5
721  wallis and futuna  2026      5

[722 rows x 3 columns]

Q23.Compute the year-over-year growth rate in the total number of earthquakes globally.

In [26]:
cursor.execute("""
               SELECT year, current_year_count, previous_year_count,
               ROUND(((current_year_count - previous_year_count) / previous_year_count) * 100, 2) AS year_over_year_change 
               FROM (SELECT year, COUNT(*) AS current_year_count, LAG(COUNT(*)) OVER (ORDER BY year) AS previous_year_count 
               FROM eq_database.earthquake_table 
               GROUP BY year) AS yearly_data 
               ORDER BY year DESC;""")
Q23_results = cursor.fetchall()
Q23_results = pd.DataFrame(Q23_results, columns=['year', 'current_year_count', 'previous_year_count', 'year_over_year_change'])
Q23_results

   year  current_year_count  previous_year_count year_over_year_change
0  2026                8233              22818.0                -63.92
1  2025               22818              18659.0                 22.29
2  2024               18659              20830.0                -10.42
3  2023               20830              20208.0                  3.08
4  2022               20208              21926.0                 -7.84
5  2021               21926                  NaN                  None

Q24. List the 3 most seismically active regions by combining both frequency and average magnitude.

In [27]:
cursor.execute("""
               SELECT country,COUNT(country) AS earthquake_count, AVG(mag) AS avg_magnitude
               FROM eq_database.earthquake_table 
               GROUP BY country 
               ORDER BY COUNT(country) DESC LIMIT 3;""")
Q23_results = cursor.fetchall()
Q23_results = pd.DataFrame(Q23_results, columns=['country', 'earthquake_count', 'avg_magnitude'])
Q23_results

     country  earthquake_count  avg_magnitude
0     alaska             34477       4.124611
1  indonesia              8687       4.496052
2     russia              6152       4.483127

Q25. For each country, calculate the average depth of earthquakes within ±5° latitude range of the equator.

In [28]:
cursor.execute("""
               SELECT country,AVG(depth_km) AS avg_depth 
               FROM eq_database.earthquake_table 
               WHERE latitude BETWEEN -5 AND 5 
               GROUP BY country 
               ORDER BY avg_depth DESC;""")
Q25_results = cursor.fetchall()
Q25_results = pd.DataFrame(Q25_results, columns=['country', 'avg_depth'])
Q25_results

                             country   avg_depth
0                        philippines  123.475438
1                   papua new guinea   72.564050
2                               peru   64.200613
3                            ecuador   62.651495
4                          indonesia   62.464919
5                           colombia   41.813256
6                             alaska   23.547251
7                       congo-uganda   14.775000
8                          venezuela   11.127000
9                           malaysia   10.762500
10                            brazil   10.556000
11                            rwanda   10.441538
12                            guyana   10.351429
13                            uganda   10.078333
14                           burundi   10.000000
15                          tanzania   10.000000
16                   kiribati region   10.000000
17                       south sudan   10.000000
18                            panama   10.000000
19                             palau   10.000000
20                          ethiopia   10.000000
21                    ecuador region    9.987687
22  democratic republic of the congo    9.921560
23                             gabon    9.818182
24                             kenya    9.799000

Q26. Identify countries having the highest ratio of shallow to deep earthquakes.

In [29]:
cursor.execute("""
               SELECT country, SUM(depth_km < 70) AS shallow_eq,
               SUM(depth_km > 300) AS deep_eq,
               ROUND(SUM(CASE WHEN depth_km <= 70 THEN 1 ELSE 0 END) / NULLIF(SUM(CASE WHEN depth_km > 300 THEN 1 ELSE 0 END), 0), 2) 
               AS shallow_to_deep_ratio 
               FROM eq_database.earthquake_table 
               GROUP BY country 
               ORDER BY shallow_to_deep_ratio DESC LIMIT 20;""")
Q26_results = cursor.fetchall()
Q26_results = pd.DataFrame(Q26_results, columns=['country', 'shallow_eq count', 'deep_eq_count', 'shallow_to_deep_ratio'])
Q26_results

,country,shallow_eq count,deep_eq_count,shallow_to_deep_ratio
0,china,1352,1,1352.00
1,peru,706,1,706.00
2,guam,465,1,465.00
3,afghanistan,256,1,256.00
4,new zealand,1398,11,127.09
5,solomon islands,750,8,93.75
6,russia,5248,98,53.56
7,vanuatu,1083,28,38.68
8,japan,4107,127,32.34
9,papua new guinea,2340,76,30.82
10,philippines,3358,121,27.75
11,indonesia,6006,285,21.07
12,italy,123,13,9.46
13,alaska,27068,3264,8.29
14,argentina,254,36,7.06
15,japan region,1383,247,5.60
16,northern mariana islands,624,128,4.88
17,tonga,1604,600,2.67
18,malaysia,4,3,1.33
19,brazil,14,14,1.00

Q27. Find the average magnitude difference between earthquakes with tsunami alerts and those without.

In [30]:
cursor.execute("""
               SELECT 
               (SELECT AVG(mag) FROM eq_database.earthquake_table WHERE tsunami = 1) AS tsunami_avg,
               (SELECT AVG(mag) FROM eq_database.earthquake_table WHERE tsunami = 0) AS no_tsunami_avg,
               (SELECT AVG(mag) FROM eq_database.earthquake_table WHERE tsunami = 1) - (SELECT AVG(mag) FROM eq_database.earthquake_table WHERE tsunami = 0) 
               AS diff;""")
Q27_results = cursor.fetchall()
Q27_results = pd.DataFrame(Q27_results, columns=['tsunami_avg', 'no_tsunami_avg', 'diff'])
Q27_results

   tsunami_avg  no_tsunami_avg      diff
0     5.416443        4.249525  1.166918

Q28. Using the gap and rms columns, identify events with the lowest data reliability (highest average error margins).

In [31]:
cursor.execute("""
               SELECT id,date, place, gap, rms 
               FROM eq_database.earthquake_table 
               ORDER BY gap DESC, rms ASC 
               LIMIT 25;""")
Q28_results = cursor.fetchall()
Q28_results = pd.DataFrame(Q28_results, columns=['id', 'date', 'place', 'gap', 'rms'])     
Q28_results

,id,date,place,gap,rms
0,nn00897599,2025-05-14,"60 km NE of Valmy, Nevada",358.18,0.1601
1,pr2024051000,2024-02-20,"77 km NW of Sandy Ground Village, Anguilla",358.00,0.1600
2,pr71508583,2026-02-23,"86 km WNW of Sandy Ground Village, Anguilla",356.00,0.2200
3,us7000denb,2021-02-14,"Andreanof Islands, Aleutian Islands, Alaska",355.00,0.3400
4,aka2026kbzasg,2026-05-22,"181 km E of Atka, Alaska",354.00,0.7000
5,pr2022227000,2022-08-15,"59 km ENE of Cruz Bay, U.S. Virgin Islands",353.00,0.6100
6,pr2022289000,2022-10-16,"78 km E of Cruz Bay, U.S. Virgin Islands",352.00,0.0700
7,pr71489653,2025-07-18,"53 km SSW of Boca de Yuma, Dominican Republic",352.00,0.1800
8,pr2022311006,2022-11-07,"58 km NE of Cruz Bay, U.S. Virgin Islands",351.00,0.1700
9,pr2021003002,2021-01-03,"87 km WNW of The Bottom, Bonaire, Saint Eustat...",351.00,0.4400
10,pr2022230002,2022-08-18,"10 km N of Cruz Bay, U.S. Virgin Islands",350.00,0.0300
11,av91047508,2022-01-21,"Rat Islands, Aleutian Islands, Alaska",350.00,0.1000
12,us6000k2l1,2023-04-02,"17 km SE of Atka, Alaska",350.00,0.2400
13,pr2021037008,2021-02-06,"90 km N of Cruz Bay, U.S. Virgin Islands",350.00,0.3800
14,pr2021028009,2021-01-28,"66 km E of Saint Croix, U.S. Virgin Islands",350.00,0.7200
15,pr2021014100,2021-01-14,"58 km N of Cruz Bay, U.S. Virgin Islands",349.00,0.0900
16,pr2021283003,2021-10-10,"60 km NNE of Cruz Bay, U.S. Virgin Islands",349.00,0.1800
17,pr2021006078,2021-01-06,"70 km ESE of Cruz Bay, U.S. Virgin Islands",349.00,0.3900
18,pr2021274004,2021-10-01,"68 km E of Cruz Bay, U.S. Virgin Islands",349.00,0.5000
19,pr2022031001,2022-01-31,"69 km ESE of Cruz Bay, U.S. Virgin Islands",349.00,0.6200
20,pr2024148000,2024-05-27,"82 km E of Cruz Bay, U.S. Virgin Islands",348.00,0.2300
21,pr2021223002,2021-08-11,"89 km E of Cruz Bay, U.S. Virgin Islands",348.00,0.2600
22,aka2026fsqlut,2026-03-22,"121 km NW of False Pass, Alaska",348.00,0.4000
23,aka2026jcdrcz,2026-05-08,"239 km S of Attu Station, Alaska",348.00,0.4000
24,pr71352418,2022-06-04,"10 km NNW of Cruz Bay, U.S. Virgin Islands",348.00,0.6100

Q29. Find pairs of consecutive earthquakes (by time) that occurred within 50 km of each other and within 1 hour.

NOTE: DATA NOT SUFFICIENT

Q30. Determine the regions with the highest frequency of deep-focus earthquakes (depth > 300 km)

In [32]:
cursor.execute("""
               SELECT country, count(country) as deep_earthquake_count, max(depth_km) AS deep_focus_earthquake 
               FROM eq_database.earthquake_table 
               WHERE depth_km > 300 
               GROUP BY country 
               ORDER BY deep_earthquake_count DESC;""")
Q30_results = cursor.fetchall()
Q30_results = pd.DataFrame(Q30_results, columns=['country', 'deep_earthquake_count', 'deep_focus_earthquake'])
Q30_results

                     country  deep_earthquake_count  deep_focus_earthquake
0                     alaska                   3264                675.265
1                       fiji                   1193                669.556
2                      tonga                    600                623.316
3                  indonesia                    285                650.655
4               japan region                    247                580.248
5                timor leste                    211                605.860
6          wallis and futuna                    163                615.533
7   northern mariana islands                    128                622.680
8                      japan                    127                501.600
9                philippines                    121                639.503
10                    russia                     98                616.509
11          papua new guinea                     76                613.786
12                 argentina                     36                616.553
13                   vanuatu                     28                683.578
14                   bolivia                     21                619.384
15                    brazil                     14                626.976
16                     italy                     13                490.230
17               new zealand                     11                448.400
18           solomon islands                      8                541.327
19               north korea                      4                644.879
20                  malaysia                      3                634.664
21                      guam                      1                416.750
22               afghanistan                      1                300.149
23                     china                      1                584.069
24                      peru                      1                648.298